# Generated by Django 3.1.7 on 2021-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210417_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
