# Generated by Django 3.1.7 on 2021-04-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210417_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='people',
            new_name='cur_people',
        ),
        migrations.AddField(
            model_name='task',
            name='need_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='pkg_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
